### ISSUE TITLE
Attention weights not initialized

### ISSUE THREAD

**Issue by k15z** [huggingface/torchMoji#11]
The [attention weights](https://github.com/huggingface/torchMoji/blob/fa69063bb0b1a9fbca6ba4bb95def7979737432c/torchmoji/attlayer.py#L31) are not initialized properly; right now, they take on random values up to 10^38, which makes training a model from scratch virtually impossible.

In contrast, the original Keras implementation uses a uniform random initialization scheme with values from -0.05 to 0.05. Obviously this doesn't affect pretrained models, but it would still be nice to have this fixed.

**Comment by bfelbo** [comment]
@thomwolf, it would be great if you have a chance to fix this. I've had multiple people come to me with problems that all originated from this underlying issue.

**Comment by thomwolf** [comment]
Ok this should be fixed by aa5818ae8dc4493749f2e4c08c273620a4e26446
Sorry for being late on that!
