### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by agoel00** [huggingface/torchMoji#24]
I'm trying to get 2304 fixed length vector embeddings for a set of tweets for my dataset.

I'm using Google Colaboratory(Python 3) and I get this error with this command

`!python3 examples/text_emojize.py --text f"This is the shit!"`

as well as using this 

`encoding = model(tokenized)`

**Comment by sb1992** [comment]
Did you mange to solve this?

**Comment by agoel00** [comment]
I was able to bypass this issue by downgrading the PyTorch version in Google Colab environment. Apparently it doesn't work with Pytorch 1.1 which Colab provides currently.

Downgrading to 1.0.1 seems to solve the problem.
