### ISSUE TITLE
How to replace Emoji ID's with actual emojis or their unicodes? Help

### ISSUE THREAD

**Issue by vidyap-xgboost** [huggingface/torchMoji#35]
Hi.
When we run [score_texts_emojis.py](https://github.com/huggingface/torchMoji/blob/master/examples/score_texts_emojis.py), we get an output like the below picture saved in a .CSV file.

<img width="355" alt="2020-06-25 (2)" src="https://user-images.githubusercontent.com/65642130/85688303-420feb80-b6ef-11ea-9e34-36f322a30821.png">

I want to convert the ID's of Emojis(Emoji_1, Emoji_2, Emoji_3, Emoji_4, Emoji_5) given into either actual emojis or their UNICODES.

Can someone help me with that?

TIA.

**Comment by setu4993** [comment]
Try using the example from [this example](https://github.com/huggingface/torchMoji/blob/198f7d4e0711a7d3cd01968812af0121c54477f8/examples/text_emojize.py#L60), starting at line 60. You can also get the text of the emoji, by not converting it to emoji by skipping line 63 (containing `emoji.emojize...`).

**Comment by vidyap-xgboost** [comment]
> Try using the example from [this example](https://github.com/huggingface/torchMoji/blob/198f7d4e0711a7d3cd01968812af0121c54477f8/examples/text_emojize.py#L60), starting at line 60. You can also get the text of the emoji, by not converting it to emoji by skipping line 63 (containing `emoji.emojize...`).

@setu4993  Thanks!
