### ISSUE TITLE
pytorch_model.bin module missing

### ISSUE THREAD

**Issue by akchaudhary57** [huggingface/torchMoji#40]
I am trying to replicate this paper as per my project proposal. Could you please assist with this?

While running 

python examples/text_emojize.py --text "I love mom's cooking\!"

I got C:\\...\\torchMoji/model/pytorch_model.bin'  No such file or directory: issue.

**Comment by mxhdiqaim** [comment]
Did you have a solution to your problem? How did you tackle it?
