### ISSUE TITLE
Finetuning does not work for more than 2 classes.

### ISSUE THREAD

**Issue by pushpankar** [huggingface/torchMoji#6]
I am getting` RuntimeError: Expected object of type Variable[torch.LongTensor] but found type Variable[torch.FloatTensor] for argument #1 'target'.` May be we need to change CrossEntropyLoss with something else.

**Comment by pushpankar** [comment]
Fixed it by replacing, `y.float()` with `y` in `loss_op`.

**Comment by pushpankar** [comment]
Also, accuracy calculation is wrong.

**Comment by julien-c** [comment]
Which version of Pytorch @pushpankar?

**Comment by pushpankar** [comment]
I am using 0.3.0.

**Comment by pushpankar** [comment]
I have made some modification. Please review the pull request.
